import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast'

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  style: 'normal'
});

export const metadata: Metadata = {
  title: "Задания для курса 'Осведомленность в области ИБ'",
  description: "Generated by create next app",
  icons: 'group.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='size-full'>
      <body
        className={`${roboto.variable} antialiased size-full`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
